#define MAJOR_VERSION "1"
#define MINOR_VERSION "1"
#define PATCH_VERSION "0"

#define VERSION MAJOR_VERSION "." MINOR_VERSION "." PATCH_VERSION

#define HEADER_PROJECT_NAME "Soteria-Vault"
#define HEADER_FORMAT "SV Format " MAJOR_VERSION